//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeDBEntities : DbContext
    {
        public ResumeDBEntities()
            : base("name=ResumeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expertises1> Expertises1 { get; set; }
        public virtual DbSet<Expertises2> Expertises2 { get; set; }
        public virtual DbSet<Section1> Section1 { get; set; }
        public virtual DbSet<SectionAbout> SectionAbouts { get; set; }
        public virtual DbSet<SectionArticle> SectionArticles { get; set; }
        public virtual DbSet<SectionService> SectionServices { get; set; }
        public virtual DbSet<SectionTestimonial> SectionTestimonials { get; set; }
        public virtual DbSet<SectionWork> SectionWorks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Expertises1h> Expertises1h { get; set; }
    }
}
